# Generated by Django 3.2.9 on 2021-11-30 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0003_auto_20211130_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='orders.address'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='orders.servicetype'),
        ),
    ]
