# Generated by Django 3.2.9 on 2021-12-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO orders_residencetype (name) VALUES ('Casa'),('Studio'),('Apartamento');"),
        migrations.RunSQL("INSERT INTO orders_servicetype (name) VALUES ('Limpeza Residencial'), ('Passadoria');")
    ]
